const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');const path=require('node:path');
const read=n=>fs.readFileSync(path.join(__dirname,'../assets',n),'utf8');
function analytics(config={},pathname='/services.html',search=''){
 const requests=[],listeners={};let reloads=0;
 const document={documentElement:{lang:'fr'},referrer:'https://example.org/private?email=secret@example.org',cookie:'',head:{append:s=>requests.push(s.src)},createElement:()=>({}),addEventListener:(n,f)=>listeners[n]=f,getElementById:()=>null};
 const location={origin:'https://ltopic.ai',hostname:'ltopic.ai',pathname,search,hash:'',reload:()=>reloads++};
 const window={LtopicConfig:config};vm.runInNewContext(read('analytics.js'),{window,document,location,URL,Set,Date});
 return {window,requests,get reloads(){return reloads},api:window.LtopicAnalytics};
}
test('missing configuration and initial refusal make zero vendor requests',()=>{const a=analytics();a.api.applyConsent({analytics:true,behavior:true});assert.equal(a.requests.length,0);const b=analytics({ga4Id:'G-TEST123',clarityId:'abc123456'});b.api.applyConsent({});assert.equal(b.requests.length,0);assert.equal(b.api.track('generate_lead'),false);});
test('GA-only consent loads once, deduplicates and drops all personal parameters',()=>{const a=analytics({ga4Id:'G-TEST123',clarityId:'abc123456'});a.api.applyConsent({analytics:true});a.api.applyConsent({analytics:true});assert.equal(a.requests.length,1);assert.match(a.requests[0],/googletagmanager/);assert.equal(a.api.track('generate_lead',{email:'secret@example.org',form_id:'contact',cta_id:'secret@example.org'},'success'),true);assert.equal(a.api.track('generate_lead',{},'success'),false);assert.equal(a.api.track('arbitrary_event'),false);const payload=JSON.stringify(a.window.dataLayer);assert.ok(!payload.includes('secret@example.org'));assert.ok(payload.includes('https://example.org'));assert.ok(!payload.includes('/private'));});
test('Clarity-only consent does not load GA; Contact and query strings exclude recording',()=>{for(const [url,query,expected] of [['/index.html','',1],['/contact.html','',0],['/en/contact.html','',0],['/index.html','?email=private',0]]){const a=analytics({ga4Id:'G-TEST123',clarityId:'abc123456'},url,query);a.api.applyConsent({behavior:true});assert.equal(a.requests.length,expected);assert.ok(a.requests.every(s=>s.includes('clarity.ms')));}});
test('withdrawal blocks future events and unloads running recorder, without reloading Contact',()=>{const a=analytics({ga4Id:'G-TEST123',clarityId:'abc123456'});a.api.applyConsent({analytics:true,behavior:true});a.api.applyConsent({});assert.equal(a.api.track('generate_lead'),false);assert.equal(a.reloads,1);const b=analytics({ga4Id:'G-TEST123'},'/contact.html');b.api.applyConsent({analytics:true});b.api.applyConsent({});assert.equal(b.reloads,0);});
function form(fetchImpl,endpoint='https://formsubmit.co/ajax/'+'a'.repeat(32)){
 const handlers={},events=[],button={disabled:true,textContent:''},fieldset={disabled:true},status={textContent:''},notice={textContent:''};
 const input={value:'PERSONAL_SENTINEL'};
 const f={elements:{namedItem:()=>input},querySelector:s=>s==='[type="submit"]'?button:s==='fieldset'?fieldset:null,addEventListener:(n,h)=>handlers[n]=h,reportValidity:()=>true,setAttribute(){},removeAttribute(){}};
 const document={documentElement:{lang:'fr'},getElementById:id=>id==='contact-form'?f:id==='contact-status'?status:notice};
 const window={LtopicConfig:{formEndpoint:endpoint},LtopicAnalytics:{track:(...args)=>events.push(args)}};
 vm.runInNewContext(read('contact-form.js'),{window,document,fetch:fetchImpl,AbortController,setTimeout,clearTimeout});
 return {button,fieldset,status,events,input,submit:()=>handlers.submit({preventDefault(){}})};
}
test('form is enabled independently of analytics consent and prevents concurrent/repeated success',async()=>{let resolve,calls=0;const f=form(()=>{calls++;return new Promise(r=>resolve=r)});assert.equal(f.fieldset.disabled,false);const pending=f.submit();await f.submit();assert.equal(calls,1);resolve({ok:true,json:async()=>({success:'true'})});await pending;await f.submit();assert.equal(calls,1);assert.equal(f.events.filter(e=>e[0]==='generate_lead').length,1);assert.ok(!JSON.stringify(f.events).includes('PERSONAL_SENTINEL'));assert.equal(f.button.disabled,true);});
test('rejected requests preserve text, restore button, and do not count as leads',async()=>{const f=form(async()=>({ok:false,json:async()=>({success:false,message:'raw provider response'})}));await f.submit();assert.equal(f.events.filter(e=>e[0]==='generate_lead').length,0);assert.equal(f.button.disabled,false);assert.equal(f.input.value,'PERSONAL_SENTINEL');assert.ok(!f.status.textContent.includes('raw provider response'));});
test('network and timeout failures never report a successful conversion',async()=>{for(const name of ['TypeError','AbortError']){const f=form(async()=>{throw Object.assign(new Error('sensitive server details'),{name})});await f.submit();assert.ok(f.status.textContent.includes('peut-être'));assert.equal(f.events.filter(e=>e[0]==='generate_lead').length,0);assert.equal(f.input.value,'PERSONAL_SENTINEL');}});
test('empty or email-based endpoints remain disabled and are never contacted',async()=>{for(const url of ['', 'https://formsubmit.co/ajax/private@example.org']){let calls=0;const f=form(()=>calls++,url);await f.submit();assert.equal(calls,0);assert.equal(f.fieldset.disabled,true);}});
